language: ruby
sudo: false
services: mongodb
cache: bundler
notifications:
  email: false
env:
  - RAILS_ENV=test
  - CI=true
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.2.4
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
  - bundle exec rake
