# SPARQL::Client configuration.
# Production references the SPARQL endpoint. Development and test use the local SQLite3 service initialized with test data

development:
  adapter: Sparql
  repository: "sqlite3:db/nomisma.sqlite3"
test: &test
  adapter: Sparql
  repository: "sqlite3:db/nomisma.sqlite3"
production:
  adapter: Sparql
  url: <%= ENV['SPARQL_URL'] || "http://127.0.0.1/FIXME" %>
